### ISSUE TITLE
"An internal error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by folke13** [karlovm/TownyWars#1] opened 2020-07-30 20:17 UTC
We performed the /twar n command and got an error from console: [Thu, 30. Jul 2020 16:21:02 EDT ERROR] null
 "An internal error occurred while attempting to perform this command"

**Comment by karlovm** [comment] 2020-08-03 07:20
The issue is resolved in discord.

**Closed as completed by karlovm** 2020-08-03 07:20 UTC
